name: 👉 Add a New Resource (EN)
description: Submit a new resource
labels:
- lang:en
- new-submission
body:
- type: markdown
  attributes:
    value: 'Thanks for taking the time to submit a new resource to the Awesome Snapmaker
      List!


      '
- type: textarea
  id: description
  attributes:
    label: Resource Description
    description: ''
    placeholder: ''
  validations:
    required: true
- type: input
  id: author_name
  attributes:
    label: Author Name
    description: ''
  validations:
    required: true
- type: input
  id: author_link
  attributes:
    label: Author Link
    description: ''
  validations:
    required: true
- type: input
  id: original_link
  attributes:
    label: Content Link (Original URL)
    description: ''
    placeholder: https://...
  validations:
    required: true
- type: dropdown
  id: difficulty
  attributes:
    label: Difficulty Level
    options:
    - BEGINNER
    - INTERMEDIATE
    - ADVANCED
  validations:
    required: true
- type: dropdown
  id: cost
  attributes:
    label: Cost
    options:
    - FREE
    - PAID
    - FREEMIUM
  validations:
    required: true
- type: dropdown
  id: language
  attributes:
    label: Language
    description: ''
    options:
    - EN
    - ZH
    - DE
    - FR
    - ES
  validations:
    required: true
- type: checkboxes
  id: machine_type
  attributes:
    label: Machine Type(s)
    description: ''
    options:
    - label: SM_2.0
    - label: ARTISAN
    - label: U1
    - label: J1/J1s
    - label: RAY
    - label: UNIVERSAL
- type: checkboxes
  id: machine_tool_type
  attributes:
    label: Machine Tool Type(s)
    description: ''
    options:
    - label: FDM
    - label: LASER
    - label: CNC
    - label: ROTARY
    - label: COMBINED
- type: checkboxes
  id: record_type
  attributes:
    label: Record Type(s)
    description: ''
    options:
    - label: ARTICLE
    - label: CREATE
    - label: DISCUSSION
    - label: DOWNLOAD
    - label: FIRMWARE
    - label: MODS
    - label: ONLINE TOOL
    - label: REPAIR
    - label: SHOP
    - label: VIDEO
- type: dropdown
  id: official_resource
  attributes:
    label: Official Snapmaker Resource?
    description: ''
    options:
    - 'No'
    - 'Yes'
  validations:
    required: true
- type: input
  id: free_tags
  attributes:
    label: Free Tags
    description: ''
    placeholder: UNOFFICIAL, cooling, petg
  validations:
    required: false
- type: input
  id: extra_button_1_label
  attributes:
    label: (Optional) Extra Button 1 - Label
    description: ''
    placeholder: Download STL
  validations:
    required: false
- type: input
  id: extra_button_1_link
  attributes:
    label: (Optional) Extra Button 1 - Link
    placeholder: https://...
  validations:
    required: false
- type: markdown
  attributes:
    value: By submitting this issue, you confirm the link is safe and valid.
