name: 👉 Добавить новую запись (RU)
description: Отправьте новый ресурс (инструмент, руководство, мод и т.д.) в 
  Awesome Snapmaker List!
labels:
  - lang:ru
  - new-submission
body:
  - type: markdown
    attributes:
      value: "Спасибо, что нашли время для добавления нового ресурса в Awesome Snapmaker
        List!\n\nПожалуйста, заполните форму ниже. После отправки наш автоматический
        бот создаст Pull Request для добавления в базу данных, и модератор сможет
        одобрить это одним кликом!\n\n"
  - type: textarea
    id: description
    attributes:
      label: Описание ресурса
      description: Дайте краткое описание, о чём этот ресурс.
      placeholder: ПРИМЕР - Это руководство охватывает лучшие настройки для…
    validations:
      required: true
  - type: input
    id: author_name
    attributes:
      label: Имя автора
      description: Кто создал этот ресурс? (Используйте своё имя или ник, если 
        это ваш ресурс)
    validations:
      required: true
  - type: input
    id: author_link
    attributes:
      label: Ссылка на автора
      description: Ссылка на профиль автора (GitHub, Thingiverse, Форум и т.д.)
    validations:
      required: true
  - type: input
    id: original_link
    attributes:
      label: Ссылка на контент (оригинальный URL)
      description: Где размещён этот ресурс?
      placeholder: https://...
    validations:
      required: true
  - type: dropdown
    id: difficulty
    attributes:
      label: Уровень сложности
      options:
        - НОВИЧОК
        - СРЕДНИЙ
        - ПРОДВИНУТЫЙ
    validations:
      required: true
  - type: dropdown
    id: cost
    attributes:
      label: Стоимость
      options:
        - БЕСПЛАТНО
        - ПЛАТНО
        - FREEMIUM
    validations:
      required: true
  - type: dropdown
    id: language
    attributes:
      label: Язык
      description: На каком основном языке написан этот ресурс?
      options:
        - AR
        - DA
        - DE
        - EN
        - ES
        - FR
        - HE
        - IT
        - PL
        - RU
        - ZH-CN
        - ZH-HK
        - EN-PIRATE
    validations:
      required: true
  - type: checkboxes
    id: machine_type
    attributes:
      label: Модели
      description: К каким машинам Snapmaker это относится? (Выберите все 
        подходящие)
      options:
        - label: SM_2.0
        - label: ARTISAN
        - label: U1
        - label: J1/J1s
        - label: RAY
        - label: УНИВЕРСАЛЬНО
  - type: checkboxes
    id: machine_tool_type
    attributes:
      label: Тип(ы) инструмента
      description: Какие модули/насадки актуальны? (Выберите все подходящие)
      options:
        - label: ЭКСТРУДЕР
        - label: ЛАЗЕР
        - label: ФРЕЗА
        - label: ПОВОРОТНЫЙ МОДУЛЬ
        - label: КОМБИНАЦИЯ
  - type: checkboxes
    id: record_type
    attributes:
      label: Тип(ы) контента
      description: Что это за ресурс? (Выберите все подходящие)
      options:
        - label: СТАТЬЯ
        - label: СДЕЛАТЬ
        - label: ОБСУЖДЕНИЕ
        - label: СКАЧАТЬ
        - label: ПРОШИВКА
        - label: МОДЫ
        - label: ОНЛАЙН-ИНСТРУМЕНТ
        - label: РЕМОНТ
        - label: КУПИТЬ
        - label: ВИДЕО
  - type: dropdown
    id: official_resource
    attributes:
      label: Официальный ресурс Snapmaker?
      description: Это официальный ресурс Snapmaker или созданный сообществом?
      options:
        - "Нет"
        - "Да"
    validations:
      required: true
  - type: input
    id: free_tags
    attributes:
      label: Свободные теги
      description: Теги через запятую (например g-code, PETG, гравировка, 
        охлаждение)
      placeholder: UNOFFICIAL, cooling, petg
    validations:
      required: false
  - type: input
    id: extra_button_1_label
    attributes:
      label: (Необязательно) Дополнительная кнопка 1 - НАДПИСЬ НА КНОПКЕ
      description: Полезно для прямых загрузок PDF/STL.
      placeholder: Download STL
    validations:
      required: false
  - type: input
    id: extra_button_1_link
    attributes:
      label: (Необязательно) Дополнительная кнопка 1 - ССЫЛКА
      placeholder: https://...
    validations:
      required: false
  - type: markdown
    attributes:
      value: Отправляя этот тикет, вы подтверждаете, что ссылка безопасна и 
        действительна.
