blank_issues_enabled: true
contact_links:
  - name: Discuss this list on the Forum
    url: https://forum.snapmaker.com/t/awesome-snapmaker-list/31346
    about: Ask questions or discuss the Awesome Snapmaker List with the community.
